/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SessionRouteRouteImport } from './pages/session.route'
import { Route as SessionIndexRouteImport } from './pages/session/index'

const SessionRouteRoute = SessionRouteRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/session': typeof SessionRouteRouteWithChildren
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/session': typeof SessionRouteRouteWithChildren
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/session' | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to: '/session'
  id: '__root__' | '/session' | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SessionRouteRoute: typeof SessionRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof SessionRouteRoute
    }
  }
}

interface SessionRouteRouteChildren {
  SessionIndexRoute: typeof SessionIndexRoute
}

const SessionRouteRouteChildren: SessionRouteRouteChildren = {
  SessionIndexRoute: SessionIndexRoute,
}

const SessionRouteRouteWithChildren = SessionRouteRoute._addFileChildren(
  SessionRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SessionRouteRoute: SessionRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
